### In this notebook we are going to cover most fundamenatal concepts of tensors using TensorFlow

📖 More specifically we are going to cover
* Introduction to tensors
* Getting informations from tensors
* Manipulating tensors
* Tensors and Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow

In [1]:
## Importing TensorFlow
import tensorflow as tf

2026-05-17 16:34:24.471562: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
print(tf.__version__)

2.16.2


In [3]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
## check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
## create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
## check the dimensions of our vector
vector.ndim

1

In [7]:
## create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
## create another matrix 
another_matrix = tf.constant([[1., 2.], 
                              [3., 4.], 
                              [5., 6.]], dtype=tf.float16) # specify the datatype of the elements 
                                                           # in the tensor with 16 bit precision (half precision)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [10]:
## number of dimensions of another_matrix
another_matrix.ndim

2

In [11]:
## creating a tensor
tensor = tf.constant([[[1, 2, 3], 
                       [4, 5, 6]], 
                      [[7, 8, 9], 
                       [10, 11, 12]], 
                      [[13, 14, 15], 
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

### Definition

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-d array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number,
                                             where 0-dimensional is scalar and 1-dimensional is a vector)

> **Creating tensor with ```tf.Variable```**

In [13]:
## creating the tensor with tf.Variable
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
## change on of the elements in changeable_tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [16]:
##try .assign() method on changeable_tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
## chaning in unchangeable_tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor


AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'


* NOTE: In case of doubt use tf.constant() and change as per need

> **Creating Random Tesnors**

Random Tensors are Tensors of some arbitary size with random numbers (weights).

In [18]:
## creating random tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # create a random tensor with normal distribution
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

In [19]:
# Are they equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

> **Shuffling the Order of elements in Tensors**

In [20]:
## shuffling is neccessary for when you want to shuffle data so the order of the data doesn't effect the learning of the model
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

In [21]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [22]:
## shuffle the order of the elements in not_shuffled
## global and operation level random seed
tf.random.set_seed(42) # global level random seed
shuffled = tf.random.shuffle(not_shuffled, seed=42)  # shuffled along the first dimension (rows)
                                                     # operation level random seed
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

> **Other ways to make tensors**

In [23]:
# Create tensors of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [24]:
# create tensor of all zeroes
tf.zeros(shape=(7,7))

<tf.Tensor: shape=(7, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

> **Turn numpy arrays on tensors**

🔑 The main differnce b/w Numpy arrays and TensorFlow tensors is that tensors can be run on a GPU m(uch faster
for numerical computing.)

In [25]:
# turn numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype= np.int32)

numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [26]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)

A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

> **Getting information from tensor**

* Shape
* Rank
* Axis or Dimension
* Size

In [27]:
tensor = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [1, 2, 3]])

In [28]:
# Get various attributes of our tensor
print("Datatype of every element:", tensor.dtype)
print("Number of dimensions (rank):", tensor.ndim)
print("Shape of tensor:", tensor.shape)
print("Elements along axis 0 (rows):", tensor.shape[0])
print("Elements along axis 1 (columns):", tensor.shape[1])
print("Total number of elements in tensor:", tf.size(tensor))
print("Total number of elements in tensor:", tf.size(tensor).numpy())

Datatype of every element: <dtype: 'int32'>
Number of dimensions (rank): 2
Shape of tensor: (3, 3)
Elements along axis 0 (rows): 3
Elements along axis 1 (columns): 3
Total number of elements in tensor: tf.Tensor(9, shape=(), dtype=int32)
Total number of elements in tensor: 9


### Indexing and Expanding Tesnors

> **Indexing Tensors**

In [29]:
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))

In [30]:
# get first two element of each dimensions
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [31]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [32]:
## get the first element from each dimension from eaqch index except the final one
rank_4_tensor[:1, :1, :1]   

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
# create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[1, 2],
                             [8, 9]])

rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [34]:
## last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 9], dtype=int32)>

In [35]:
# add in extra dimension in rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # ... every axis before
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[8],
        [9]]], dtype=int32)>

In [36]:
# Alternative of tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[8],
        [9]]], dtype=int32)>

In [37]:
# expand the 0-axis
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [8, 9]]], dtype=int32)>

In [38]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[8, 9]]], dtype=int32)>

### Manipulating Tensors

> **Tensor Operartions**

`+`, `-`, `*`, `/`

In [39]:
# adding the scalar to tensor
tensor = tf.constant([[3, 5],
                      [7, 9]])

tensor + 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8, 10],
       [12, 14]], dtype=int32)>

In [40]:
# original tensor in unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 5],
       [7, 9]], dtype=int32)>

In [41]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 50],
       [70, 90]], dtype=int32)>

In [42]:
# Subtraction
tensor - 7

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-4, -2],
       [ 0,  2]], dtype=int32)>

In [43]:
# We can use tensorflow builtin function too
# efficient
tf.multiply(tensor, 9)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[27, 45],
       [63, 81]], dtype=int32)>

In [44]:
A = tf.constant([[1, 2],
                 [3, 4]])

B = tf. constant([[1, 2, 5],
                 [3, 4, 6]])

# tf.multiply(A, B) # Hadmard product rather than matrix multiplication, need the same dimension
A @ B # Matrix multiplication just like numpy

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7, 10, 17],
       [15, 22, 39]], dtype=int32)>

### Matrix Multiplication in tensorflow

> **In ```Machine Learning``` Matrix Multiplication is one of the most common operation**

In [45]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[3 5]
 [7 9]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 44,  60],
       [ 84, 116]], dtype=int32)>

In [46]:
A = tf.constant([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

B = tf.constant([[1, 2],
                 [7, 8],
                 [6, 5]])

A, B

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [7, 8],
        [6, 5]], dtype=int32)>)

In [47]:
# transpose of matrix
tf.transpose(A), tf.transpose(B)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 7, 6],
        [2, 8, 5]], dtype=int32)>)

**The dot Product**

Matrix Multiplication is also referred to as the dot product.

We can perform matrix multilpication using
* `tf.matmul()`
* `tf.tesnordot()`
* `@` symbol

In [48]:
tf.matmul(A, B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 33,  33],
       [ 75,  78],
       [117, 123]], dtype=int32)>

In [49]:
tf.tensordot(A, B, 
             axes=1,
             name='Matrix Multiplication')

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 33,  33],
       [ 75,  78],
       [117, 123]], dtype=int32)>

### Changing the datatype of a tensor

In [50]:
tf.__version__

'2.16.2'

In [51]:
# creating a new tensor with default data type
X = tf.constant([1.7, 7.4])
X.dtype

tf.float32

In [52]:
Y = tf.constant([3, 7])
Y.dtype

tf.int32

In [53]:
# change from float32 to float16
## Reduce Precision
## 16 bit is faster than 32 bit
A = tf.cast(X, dtype=tf.float16)
A

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [54]:
# change from int32 to float32
B = tf.cast(Y, dtype=float)
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 7.], dtype=float32)>

In [55]:
## Getting the absolute value
A = tf.constant([-3, -5])
A

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-3, -5], dtype=int32)>

In [56]:
## abs values 
tf.abs(A)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

### Aggregating tensors
> **Aggregating tensor -> condensing them from multilple values down to a smaller values**

* Min
* Max
* Mean 
* Sum and more ...

In [57]:
## create a ransom tensor
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([83, 16,  9, 36, 47,  4, 69, 54, 71, 82, 59, 15, 97, 47,  7, 20, 99,
        4, 82, 90, 75, 38, 16, 17, 26, 61, 30, 80, 66, 16,  4, 61, 80, 64,
       89, 98, 21, 51, 42, 35, 81, 52, 40, 72, 40, 12,  6, 65, 49, 17])>

In [58]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [59]:
# find the minimum
tf.reduce_min(E), np.min(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=4>, 4)

In [60]:
# find the maximum
tf.reduce_max(E), np.max(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=99>, 99)

In [61]:
# find the meqan
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [62]:
# sum of tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2395>

In [63]:
## standard devidation and variance of tesnor
''' 
    The issue is that tf.math.reduce_variance and tf.math.reduce_std require the input 
    tensor to be a floating-point (decimal) or complex type. TensorFlow doesn't automatically 
    "cast" your integers to floats for these specific operations because integer division and 
    variance math can get messy.
'''
E = tf.cast(E, dtype=float)
print('Standard deviation of the tensor: ', tf.math.reduce_variance(E))
print('Variance of the tensor: ', tf.math.reduce_std(E))

Standard deviation of the tensor:  tf.Tensor(846.77, shape=(), dtype=float32)
Variance of the tensor:  tf.Tensor(29.099314, shape=(), dtype=float32)


In [64]:
## Alternarive for variance
import tensorflow_probability as tfp
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([67, 85, 74, 31, 20, 51, 92,  3, 11, 82, 89, 61, 51, 10, 53, 38, 73,
       23, 87, 61, 11, 11, 12, 35, 82, 38, 47, 19, 52, 82, 51, 91,  8, 84,
       99, 74, 92, 35, 72, 91, 53, 45, 76, 59, 52, 88, 85, 19,  8, 81])>

In [65]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=837>

### Find the positional maximum and minimum

In [66]:
## create a new tensor for finding min and max
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [67]:
# Index of our lagest value position
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [68]:
# find the positional max
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [69]:
# find the maximum value of 
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [70]:
# cheeck for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [71]:
## position of minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [72]:
# value at argmin
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor

In [73]:
## create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [74]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [75]:
G_squeezed = tf.squeeze(G)  # Reduce to dimension 1
G_squeezed, G_squeezed.shape, G_squeezed.ndim

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]),
 1)

> **OneHotEncoding**

In [76]:
# create a list of indices
some_list = [0, 1, 2, 3]  # could be red, green, blue, purple

# one hot encoding our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

## Tensor maths

In [77]:
# tf.mayth
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [78]:
## squaring
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [79]:
## raise error for value of int32
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [ ]:
## sqrt
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# find the log
tf.math.log(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Log}}; Op<name=Log; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Log] name: 

In [80]:
tf.math.log(tf.cast(H, dtype='float'))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensor and Numpy

TensorFlow interacts beautifully with numoy array

In [81]:
# create a tensor from numpy array
J = tf.constant(np.array([3., 6., 9.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 6., 9.])>

In [82]:
## convert tensory back to numpy array
np.array(J), type(np.array(J))

(array([3., 6., 9.]), numpy.ndarray)

In [83]:
# convert tesnor J to a Numpy array
J.numpy(), type(J.numpy())

(array([3., 6., 9.]), numpy.ndarray)

In [84]:
## The default type for each will be slightly different
numpy_J = tf.constant(np.array([3., 7., 10]))
tensor_J = tf.constant([3., 7., 10.])

# check the dtype
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## GPU accel

In [85]:
# finding access to GPU
tf.config.list_logical_devices(), tf.config.list_physical_devices()

([LogicalDevice(name='/device:CPU:0', device_type='CPU')],
 [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')])

In [86]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


**Note: If you have CUDA enabled GPU TensorFlow will automarically use it**